export const PizzaData = [
  {
    id: 1,
    url: "https://www.dominos.co.in//files/items/IndianTandooriPaneer.jpg",
    price: 349,
    title: "Indi Tandoori Paneer",
    body: "Basically this is just steeping oreos in milk until they are soft enough to be totally combined with the milk. · Vanilla ice cream.",
  },
   {
    id: 2,
    url: "https://www.dominos.co.in//files/items/Farmhouse.jpg",
    price: 289,
    title: "Farm House",
    body: "Basically this is just steeping oreos in milk until they are soft enough to be totally combined with the milk. · Vanilla ice cream.",
  },
  
   {
    id: 3,
    url: "https://www.dominos.co.in//files/items/Peppy_Paneer.jpg",
    price: 249,
    title: "Peppy Paneer",
    body: "Basically this is just steeping oreos in milk until they are soft enough to be totally combined with the milk. · Vanilla ice cream.",
  },
   {
    id: 4,
    url: "https://www.dominos.co.in//files/items/Paneer_Makhni.jpg",
    price: 279,
    title: "PANEER MAKHANI",
    body: "Basically this is just steeping oreos in milk until they are soft enough to be totally combined with the milk. · Vanilla ice cream.",
  },
   {
    id: 5,
    url: "https://www.dominos.co.in//files/items/Fresh_Veggie.jpg",
    price: 249,
    title: "FRESH VEGGIE",
    body: "Basically this is just steeping oreos in milk until they are soft enough to be totally combined with the milk. · Vanilla ice cream.",
  },
   {
    id: 6,
    url: "https://www.dominos.co.in//files/items/Digital_Veggie_Paradise_olo_266x265.jpg",
    price: 222,
    title: "VEGGIE PARADISE",
    body: "Basically this is just steeping oreos in milk until they are soft enough to be totally combined with the milk. · Vanilla ice cream.",
  },
  {
    id: 7,
    url: "https://www.dominos.co.in//files/items/Margherit.jpg",
    price: 299,
    title: "Margherita",
    body: "Basically this is just steeping oreos in milk until they are soft enough to be totally combined with the milk. · Vanilla ice cream.",
  },
  {
    id: 8,
    url: "https://www.dominos.co.in//files/items/Mexican_Green_Wave.jpg",
    price: 279,
    title: "Mexican Green Wave",
    body: "Basically this is just steeping oreos in milk until they are soft enough to be totally combined with the milk. · Vanilla ice cream.",
  },
  {
    id: 9,
    url: "https://www.dominos.co.in//files/items/Deluxe_Veggie.jpg",
    price: 199,
    title: " Deluxe Veggie",
    body: "Basically this is just steeping oreos in milk until they are soft enough to be totally combined with the milk. · Vanilla ice cream.",
  },
];
