export const BurgerData = [
  {
    id: 1,
    url: "https://mcdloamenu.uk/wp-content/uploads/2024/11/Crispy-Veggie-Burger1.webp",
    price: 199,
    title: "Crispy Veggie Burger",
    body: "Basically this is just steeping oreos in milk until they are soft enough to be totally combined with the milk. · Vanilla ice cream.",
  },
   {
    id: 2,
    url: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/6/21/06354d09-be1b-406c-86b5-49dc9b5062d1_2f80f39e-c951-4ca6-8fca-a243a18c3448.png",
    price: 299,
    title: "Veg Maharaja Mac Burger",
    body: "Basically this is just steeping oreos in milk until they are soft enough to be totally combined with the milk. · Vanilla ice cream.",
  },
   {
    id: 3,
    url: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/6/22/fb912d21-ad9d-4332-b7cf-8f65d69e2c47_1fa5998c-b486-449a-9a88-2e61cf92ff77.png",
    price: 215,
    title: "McSpicy Paneer Burger",
    body: "Basically this is just steeping oreos in milk until they are soft enough to be totally combined with the milk. · Vanilla ice cream.",
  },
   {
    id: 4,
    url: "https://b.zmtcdn.com/data/dish_photos/c00/9586e0c428a7ae3816be6a5ed8045c00.jpeg",
    price: 179,
    title: "McVeggie Double Patty Burger",
    body: "Basically this is just steeping oreos in milk until they are soft enough to be totally combined with the milk. · Vanilla ice cream.",
  },
   {
    id: 5,
    url: "https://b.zmtcdn.com/data/dish_photos/168/2293092765c111f2cc3b9f9fe9d44168.png",
    price: 222,
    title: "McSpicy Deluxe Paneer Burger",
    body: "Basically this is just steeping oreos in milk until they are soft enough to be totally combined with the milk. · Vanilla ice cream.",
  },
   {
    id: 6,
    url: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/8/29/1a9faafd-b523-40a2-bdc6-f35191cfcf4a_0c462cb4-3843-4997-b813-dc34249b7c91.png",
    price: 269,
    title: "McSpicy Premium Veg Burger",
    body: "Basically this is just steeping oreos in milk until they are soft enough to be totally combined with the milk. · Vanilla ice cream.",
  },
  {
    id: 7,
    url: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/167aeccf27bab14940fa646c8328b1b4",
    price: 149,
    title: "Mexican McAloo Tikki Burger NONG",
    body: "Basically this is just steeping oreos in milk until they are soft enough to be totally combined with the milk. · Vanilla ice cream.",
  },
  {
    id: 8,
    url: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/cda0e2d51420a95fad28ad728914b6de",
    price: 199,
    title: "Mexican McAloo Tikki Double Patty Burger",
    body: "Basically this is just steeping oreos in milk until they are soft enough to be totally combined with the milk. · Vanilla ice cream.",
  },
  {
    id: 9,
    url: "https://jainslittleindia.com/wp-content/uploads/2024/04/Burger.webp",
    price: 199,
    title: "McVeggie Burger",
    body: "Basically this is just steeping oreos in milk until they are soft enough to be totally combined with the milk. · Vanilla ice cream.",
  },
];
